Can Message Rate Limiting
Northeastern-Electric-Racing/ShepherdBMS-2 pull request #132
Opened 2024-11-01 16:46 UTC by caiodasilva2005

## Changes

added an interface to rate limit can messages

## To Do

- [ ] define the id of all CAN messages that need to be rate limited

Closes #127

2024-11-02 00:36 UTC, Sabramz requested changes, later dismissed
your google doc

2024-11-07 16:37 UTC, Sabramz requested changes

2024-11-07 16:37 UTC, Sabramz commented on Core/Src/compute.c
> +	bms_can_msgs[DISCHARGE].len = 8;
The length of the message should be defined where the CAN message is defined now where it should be sent.

2024-11-07 16:37 UTC, Sabramz commented on Core/Src/compute.c
> +	can_msg_t acc_status_msg;
You should put message lengths in the config since they do not change and are properties of the message.

2024-11-07 16:53 UTC, jr1221 commented
This is gonna hella conflict with my CAN busy fixups, so you merge first and ill refactor it.

2024-11-12 21:54 UTC, Sabramz approved these changes
It works

2024-11-12 21:55 UTC, merged